services:
  core:
    image: tuanona/tom-core:0.0.1  # Sesuaikan dengan username Docker Hub Anda
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      SURFACE_API: ${SURFACE_API:-http://surface}

  surface:
    image: tuanona/tom-surface:0.0.1 # Sesuaikan dengan username Docker Hub Anda
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      CORE_API: ${CORE_API:-http://core:8080}
    depends_on:
      - core