# docker-compose.yml
services:
  core:
    image: tuanona/tom-core:latest
    ports:
      - "8080:8080"  # Expose ke internet
    environment:
      - ALLOW_ORIGINS=* # Atau whitelist domain

  surface-runner:
    image: tuanona/tom-surface:latest
    ports:
      - "80:80"
    environment:
      - CORE_API=http://core:8080