services:
  core:
    image: tuanona/tom-core:0.0.4
    ports:
      - "8085:2000"
    networks:
      - benang

  surface:
    image: tuanona/tom-surface:0.0.4
    ports:
      - "8082:1000"
    depends_on:
      - core
    networks:
      - benang

networks:
  benang:
    driver: bridge